#Github Action Part-1 - Basics
#
# CopyLeft (c) by AlexR 2026.
#----------------------------------------
name: My-GitHubActions-Basics

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in testing
        run : echo "Hello World from Testing job"


  my_deploy:
    runs-on: ubuntu-latest
    needs: my_testing
    
    steps:
      - name: Print Hello Message in Deploy
        run : echo "Hello World from Deploy job"
